// Well, generated by GPT.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define SIZE 512

// Initialize matrix with random values
void initMatrix(int matrix[SIZE][SIZE]) {
  for (int i = 0; i < SIZE; i++) {
    for (int j = 0; j < SIZE; j++) {
      matrix[i][j] = rand() % 100; // Random values between 0 and 99
    }
  }
}

// Multiply matrices a and b, put the result in result
void multiplyMatrices(int a[SIZE][SIZE], int b[SIZE][SIZE],
                      int result[SIZE][SIZE]) {
  int i, j, k;
  for (i = 0; i < SIZE; i++) {
    for (k = 0; k < SIZE; k++) {
      for (j = 0; j < SIZE; j++) {
        result[i][j] += a[i][k] * b[k][j];
      }
    }
  }
}
// Print the matrix
int sumMatrix(int matrix[SIZE][SIZE]) {
  int sum = 0;
  for (int i = 0; i < SIZE; i++) {
    for (int j = 0; j < SIZE; j++) {
      sum += matrix[i][j];
    }
  }
  return sum;
}

int main() {
  // Initialize random seed
  srand(time(NULL));

  int a[SIZE][SIZE];
  int b[SIZE][SIZE];
  int result[SIZE][SIZE];

  // Initialize matrices with random values
  initMatrix(a);
  initMatrix(b);

  // Multiply matrices a and b
  multiplyMatrices(a, b, result);

  fprintf(stderr, "%d\n", sumMatrix(result));

  return 0;
}